Добавлен метод вывода общих по лайкам фильмов между пользователями
Balu1294/java-filmorate pull request #9
Opened 2024-05-09 15:03 UTC by Ivinman

Тесты по постману прошли

2024-05-10 14:11 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +            @Override
для чего нужен over? rowMap есть же в текущем коде его использовать нельзя?

2024-05-10 14:13 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        SqlRowSet userFilms = jdbcTemplate.queryForRowSet("select film_id from likes where film_id in (" +
примерно так не проще? 
"SELECT u.film_id " +
                        "FROM likes as u " +
                        "INNER JOIN (SELECT film_id FROM likes WHERE user_id = ? ) as f " +
                        "ON u.film_id = f.film_id " +
                        "WHERE user_id = ? ;", friendId, userId);

2024-05-10 14:14 UTC, xakepon commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sqlQuery = "select f.*, m.name as mpa_name from films as f  join mpa as m on  f.mpa_id=m.id " +
по хорошему надо все вытащить одним запросом, чтобы более экономично обращаться с запросами к БД

2024-05-10 14:16 UTC, xakepon requested changes
Напишу как пишет мой ревьюер - код отличный! все сделал супер! посмотри мои комментарии, если можешь то попробовать бы сделать так

2024-05-11 14:18 UTC, Ivinman commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +            @Override
Согласен, лишний раз написал
Исправил

2024-05-11 14:19 UTC, Ivinman commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        SqlRowSet userFilms = jdbcTemplate.queryForRowSet("select film_id from likes where film_id in (" +
Согласен, перемудрил в своём варианте.
Взял этот полностью, работает

2024-05-11 14:21 UTC, Ivinman commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sqlQuery = "select f.*, m.name as mpa_name from films as f  join mpa as m on  f.mpa_id=m.id " +
Попытался, но мне надо чтобы в запросе было значение из этого же запроса. Не понимаю как это сделать в один запрос

2024-05-11 14:21 UTC, Ivinman commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    @Override
Добавил

2024-05-13 18:08 UTC, xakepon approved these changes

2024-05-13 19:06 UTC, merged